apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-radu-test
spec:
  nodeName: k8s-node1 # schedule pod to specific node
  containers:
  - name: ubuntu-radu-test
    image: radut/ubuntu
    imagePullPolicy: IfNotPresent
    command: ["sleep"]
    args: ["infinity"]
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "200m"
  restartPolicy: Never
