# -- mode: ruby --
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = 'ubuntu/focal64'
  config.vm.hostname = "k8s-node2"

  config.vm.network "private_network", ip: "172.16.16.21", :adapter => 2
  config.vm.synced_folder "./vagrant_data", "/vagrant_data"
#  config.vm.synced_folder "/work", "/work"

  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      "modifyvm", :id,
      "--paravirtprovider", "default"
    ]
    vb.gui = false

    vb.memory = "4096"
    vb.cpus = "4"
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo bash /vagrant_data/linux.sh --with-docker --with-kubernetes --disable-swap --vm
  SHELL
end

