VAGRANTFILE_API_VERSION = '2'
VMNAME = 'ceph-aio'
#vagrant plugin install vagrant-disksize

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.username = 'vagrant'

  if ENV['username'] != 'vagrant'
    config.ssh.username = ENV['username']
  end

  config.vm.box = 'ubuntu/bionic64'
  config.disksize.size = '50GB'
  #config.vm.network 'forwarded_port', guest: 8080, host: 8880
  #config.vm.network "public_network", bridge: "bridge0"
  config.vm.network "private_network", ip: "192.168.10.10"
  config.vm.define VMNAME
  config.vm.hostname = VMNAME

  config.vm.provider "virtualbox"

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end


  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.provision "shell", inline: "chmod +x /vagrant/*.sh && /vagrant/ceph-aio-deploy.sh"
end
